config/routes.rb
Rails.application.routes.draw do
  resources :players, only: :new do
    collection { post "create_game" }
  end

  resources :games, param: :join_code, only: :show do
    member do
      resources :players, only: [:create, :destroy] do
        member { post "kick" }
      end
      post "start"
      post "stop"
    end
  end

  root to: "players#new"
end

app/models/game.rb
class Game < ApplicationRecord
  acts_as_paranoid

  has_many :players, dependent: :destroy
  has_many :rounds,  dependent: :destroy
  has_many :templates, through: :rounds
  has_many :sources,   through: :players
  has_many :memes,     through: :players
  has_many :messages

  before_create :generate_join_code

  validate :player_minimum_reached

  def start
    PlayerChannel.broadcast_to(master, partials: {options: ""})
    reset_score
    advance_round
  end

  def stop
    update_attribute(:playing, false)
    BroadcastGameJob.perform_later(self, :stop)
    sources.each(&:destroy)
    rounds.each(&:destroy)
  end

  def reset_score
    players.each { |player| player.update_attribute(:score, 0) }
  end

  def advance
    anyone_win? ? stop : advance_round
  end

  def advance_round
    active_players.each(&:discard_played_sources)
    deal_sources
    Round.create(game: self)
  end

  def deal_sources
    players.each do |player|
      (self.source_count - player.active_sources.count).times do
        Source.create(player: player)
      end
    end
  end

  def anyone_win?
    players.any? { |player| player.score >= self.max_score }
  end

  def round
    ordered_rounds.last
  end

  def prev_round
    ordered_rounds.second_to_last
  end

  def ordered_rounds
    rounds.order("created_at ASC")
  end

  def master
    ordered_players.first
  end

  def ordered_players
    players.order("created_at ASC")
  end

  def active_players
    players.reject(&:inactive?)
  end

  def revalidate
    players.reload
    stop unless self.valid?
    self.destroy if players.count < 1
  end

  private

  def generate_join_code
    self.join_code = loop do
      code = Random.new.rand(1000..9999)
      break code unless Game.exists?(join_code: code)
    end
  end

  def player_minimum_reached
    return unless self.playing && self.players.count < 3
    errors.add(:base, "not enough players")
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :game_initialize

  def start
    return unless @game.update(game_params.merge(playing: true))
    @game.start
    render :show
  end

  def stop
    @game.stop
  end

  def show
    render :new_player if current_player.nil?
  end

  private

  def game_params
    params.permit(:max_score, :public, :join_midgame, :source_count)
  end

  def game_initialize
    @game = Game.find_by(join_code: params[:join_code]) or record_not_found
    return if current_player&.game == @game
    current_player&.destroy
    cookies.delete(:player_id)
    if @game&.persisted?
      render :new_player
    else
      redirect_to root_url
    end
  end
end

app/helpers/games_helper.rb
module GamesHelper
  def player_classes(player)
    return "czar"    if player.czar?
    return "playing" if player.playing?
    return "winner"  if player.winner?
    return ""
  end

  def hand_classes(player)
    return "noclick" if player.ready? || player.czar?
    return ""
  end

  def memes_classes(player)
    return "noclick" unless player.czar?
    return ""
  end

  def display_memes?(player)
    player.ready? || player.inactive?
  end
end

app/views/games/_buttons.html.erb
<div class="buttons">
  <% if current_player.czar? %>
    <button id="selectMeme" onclick="selectMeme()">Select Meme</button>
  <% else %>
    <button id="playHand" onclick="playHand()" disabled>Play Hand</button>
  <% end %>
</div>

app/views/games/_hand.html.erb
<% if !game.playing %>
  <span>Please wait for the host to start the game.</span>
<% elsif current_player.active_sources.any? %>
  <%= tag.div(class: "hand-container " + hand_classes(current_player)) do %>
    <div class="hand">
      <div class="hand-resize">
        <% current_player.active_sources.each do |source| %>
          <div class="hand-img">
            <%= image_tag(source.path, height: "100px", data: {source_id: source.id}) %>
          </div>
        <% end %>
      </div>
    </div>
    <% if current_player.czar? %>
      <%= tag.div(class: "czar-hand") do %>
        <span>You are the Czar. When everyone is ready, select the best meme.</span>
      <% end %>
    <% end %>
  <% end %>
<% else %>
  <span>Please wait until next round for the cards to be distributed.</span>
<% end %>

app/views/games/_main.html.erb
<% return unless game.playing %>
<% if display_memes?(current_player) %>
  <%= tag.div(class: memes_classes(current_player)) do %>
    <% if game.active_players.all?(&:ready?) %>
      <%= render game.round.memes_shuffled %>
    <% else %>
      <div class="waiting">Waiting for other players...</div>
    <% end %>
  <% end %>
<% else %>
  <%= render game.round.template %>
<% end %>

app/views/games/_options.html.erb
<% return if game.playing || !current_player.master? %>

<%= form_with url: start_game_path(game.join_code) do |f| %>
  <%= f.label :max_score, "Max score" %>
  <%= f.number_field :max_score, value: game.max_score, min: 3, max: 20 %>
  <br/>
  <%= f.label :source_count, "Source count" %>
  <%= f.number_field :source_count, value: game.source_count, min: 5, max: 10 %>
  <br/>
  <%= f.label :join_midgame, "Allow joining mid-game" %>
  <%= f.check_box :join_midgame, checked: game.join_midgame %>
  <br/>
  <%= f.submit "Start" %>
<% end %>

app/views/games/_scoreboard.html.erb
<div class="scoreboard">
  <span>Players</span>
  <table>
    <% game.ordered_players.each do |player| %>
      <%= tag.tr(class: player_classes(player), data: {player_id: player.id}) do %>
        <td><span class="name"><%= player.name %></span></td>
        <td><span class="score"><%= player.score %></span></td>
        <% next unless current_player.can_kick?(player) %>
        <td>
          <%= link_to(kick_player_path(game.join_code, player.id), method: :post) do %>
            <%= octicon("circle-slash", class: "click-icon") %>
          <% end %>
        </td>
      <% end %>
    <% end %>
  </table>
</div>

app/views/games/new_player.html.erb
<%= form_with url: players_path(@game.join_code) do |f| %>
  <%= f.text_field :name, placeholder: "username" %><br/>
  <%= f.submit "Join game" %>
<% end %>

app/views/games/show.html.erb
<div id="game">
  <div class="head">
    <span class="title">Memes Against Humanity</span>
    <%= button_to("Leave", player_path(@game.join_code, current_player.id), method: :delete) %>
    <%= button_to("Stop game", stop_game_path(@game.join_code)) if current_player.master? %>
  </div>

  <div class="main">
    <div id="options"><%= render "options", game: @game %></div>
    <div id="main"><%= render "main", game: @game %></div>
  </div>

  <div class="sidebar">
    <div id="scoreboard"><%= render "scoreboard", game: @game %></div>

    <div id="messages">
      <div class="messages"><%= render @game.messages %></div>
    </div>
    <textarea id="chatbox" rows="1" placeholder="Send a message..."></textarea>

    <div id="buttons"><%= render "buttons", game: @game %></div>
  </div>

  <div class="bottom">
    <div id="hand"><%= render "hand", game: @game %></div>
  </div>
</div>